### PR TITLE
Add Android Features 'isBluetoothAvailable' & 'openBluetoothSettings'

### PR DESCRIPTION
**Pull request by woodrufs**
## Description
This pull request adds two features for Android devices. This PR came up after discussion #106.

1) `isBluetoothAvailable(): void` - This method acts as a check to ensure Bluetooth is a supported feature on the Android device being used. One use case for this is in Zebra scanners that do not have Bluetooth and instead use their own SDK. 

2) `openBluetoothSettings(): void` - This method allows a developer to programmatically open Android's Bluetooth Settings activity.

## Testing
* Performed on Android device as well as an Android emulator (where Bluetooth is not supported)
  * Used react-native-bluetooth-classic-example as sandbox
    * Modified App.js's `render` method to return a different view when Bluetooth not detected
      * Instead of `DeviceListScreen` or `ConnectionScreen`
    * Added button to test openBluetoothSettings

### CODE REVIEW

**Comment by woodrufs** [comment]
Hey @kenjdavidson,

I took a stab at this. I would rather not disrupt anyone with this, so I didn't modify `isBluetoothEnabled`. I am also not very familiar with Java, so I apologize if I missed anything. Please let me know what you think. Also, feel free to make any updates that you would like!

**Comment by kenjdavidson** [comment]
If you're not supporting these functions on IOS, you'll need to throw the appropriate message stating that they are not currently supported on IOS.  At this point in time, they'll throw an exception - just not a nice one.

Please use the other Android only methods as baselines for handling new Android only functionality.

I'd prefer that you looked into the IOS side to see if they are possible, and implement them (as a best case) or comment on how I can implement them later (worst case).  But as a minimum they should throw correctly.

**Comment by kenjdavidson** [comment]
`/docs/` also needs to be updated with the recent additions.

**Comment by kenjdavidson** [comment]
Sorry, I just merged a bunch of stuff.  Could you rebase these changes and I'll merge the request.

**Comment by woodrufs** [comment]
@kenjdavidson,
I've updated the branch. I noticed I missed a documentation update in `api-overview.mdx` too, so I pushed an update for that too.

**Comment by woodrufs** [comment]
Danget - prettier is being a pain with the markdown files and messing with a lot of the syntax. Picking sections of the changes it is making on save made me remove a section of the docs in the last update. Fixing.

**Comment by woodrufs** [comment]
Fixed. Sorry about that.
Also, I tried to run the iOS version of the example app, but the app hard errors for me on initialization. I wasn't able to figure out the cause. I was getting an error with a bare repo that did not contain any of my changes. Any chance you have the same issue with iOS?

**Comment by kenjdavidson** [comment]
Computers are shit. Haha. I'm on after school duty now. So no rush. I'll look tomorrow.

**Comment by kenjdavidson** [comment]
Ios is a pain in the ass. You need the protocolStings xml file to start the app. I think I'm the only person actually using this library for ios development because its so proprietary.

I'll try it with my devices when I get a chance.

**Comment by woodrufs** [comment]
That was it, thanks. I had to add that entry to the plist. The iOS app runs as expected.

**Comment by kenjdavidson** [comment]
Hey, don't forget to submit the pull request for the `react-native-bluetooth-classic-apps` project.  I think you commented on here that you made some changes to test both new functions.

thanks again.

**Comment by woodrufs** [comment]
Hey.... Thank you! This is nothing compared to what you have done. I need to do some cleanup first, but I will put something together. Any chance you know why VSCode is picking up so many formatting changes (attaching an example as a screenshot below)? I see a prettier and eslint config, so I am a bit confused why I am getting all these changes. I want to contribute, but I don't want to interfere with your code styling.
Screen Shot 2021-04-28 at 8 55 50 AM

**Comment by kenjdavidson** [comment]
Ya, they fight with each other in VSCODE when they are both disabled.  I probably made the change globally instead of project specific which is why it's so annoying.

If you google for something like `VSCODE prettier and eslint` you'll find some configuration options that you need to turn off in your VSCODE properties.

I'll open a task for me to make the changes locally instead of globally when I get a chance.

**Pull request merged**
