### PR TITLE
Add listening functionality

### PR DESCRIPTION
**Pull request by tpettrov**
Added functionality so the app can receive connection requests. Please review and edit if you find it useful.

### CODE REVIEW

**Comment by kenjdavidson** [comment]
Hey. I saw this.  Have to look around and see if it's doable on IOS. The main goal was of the project initially was to get Android and ios online with each other.  Which I don't think is doable with external accessory, but apparently with latest corebluetooth there is classic functionality. It's just very limited docs at the moment. 

What do you use to connect to the phone with?  Another phone? Or a specialized peripheral?

**Comment by tpettrov** [comment]
I use it to connect specialized peripheral to the phone.

**Comment by kenjdavidson** [comment]
Righ ton. The next goals I have are the set Encoding, since I need it for my company, and the ability to configer different data parsers, which would be beneficial I think and finally refactoring the Android service to be more like ios where it implements a device and keeps the buffer with it, to allow for multiple devices. 

But I'll keep this open incase others need it too.

**Comment by tpettrov** [comment]
Yes for now I haven't experienced problems and my main test are phone <-> phone connections. I have one (happens 1 out of 15 times) which I plan to debug if any time available but it's related to resolving the promise from the listening with the connected device as a result. Sometimes there is a successful connection but the promise is not resolved...

**Comment by kenjdavidson** [comment]
Ok cool. When we get that sorted out I'llwe can pull it in. How opposed are you to:

- renaming accept instead of listen to match most socket requests 
- put in the option for a timeout

Thoughts?

**Comment by kenjdavidson** [comment]
With regards to the removal of the sleep, was it causing issues?  It was a hold over from the original `react-native-bluetooth-serial` project, I don't think it would be an issue, but it might be better to have it configurable.

**Comment by hpstuff** [comment]
hey @kenjdavidson the sleep was causing significant delay when you transfer data for long period, and since `.available()` wasn't use to create the correct buffer size removing the condition and the sleep give better performance and do not occupy the cpu because [`.read`](https://developer.android.com/reference/java/io/InputStream.html#read())  is blocking method.

**Comment by kenjdavidson** [comment]
Makes sense, we're just using it as a one off manual scan using our hardware, so the fact that this is working well(ish) for you guys doing a lot more data transfer is promising.  I'll try to get this merged (along with the IOS matching code) done sometime this weekend or early next week.

**Comment by tpettrov** [comment]
> 
> 
> Ok cool. When we get that sorted out we can pull it in. How opposed are you to:
> 
>     * renaming accept instead of listen to match most socket requests
> 
>     * put in the option for a timeout
> 
> 
> Thoughts?

Sorry for the late answer. I personally prefer to use the listen but understand your argument for accept. So yes I don't mind changing it. As for the timeout I'll try to do that too. All of this probably will come in another pull request. @hpstuff has made a branch (feature/base64) with encoding in base64 for the received data as a option, and will soon be in master. You can review that too and decide if you want it as a pull request.

**Comment by kenjdavidson** [comment]
I'll take a look at the @hpstuff branch, the very first issue I opened (and issue that was opened) was the fact that someone needed to return different data.  What i'd like to do is be able to configure an Interface/Delegate that will convert the data as needed.

For example:
- OnDataReceivedStringParser
- OnDataReceivedBase64Parser
- Etc.

So that it's easily configurable by just doing

new RNBluetoothClassicPackage(ConfigurationBuilder().withParser(new OnDataReicevedXXXParser()));

Or something along those lines, this would be the optimal end game for managing how data is handled between the device and the Javascript.

**Pull request closed without merging**
