### PR TITLE
fix podspec

### PR DESCRIPTION
**Pull request by iamandiradu**
add '/ios' to the path in Podfile

### CODE REVIEW

**Comment by kenjdavidson** [comment]
Awesome, thanks for this. 

Is the update from react native 0.41.2 to 0.60. 0 required? I don't know if I'm ready to go through all the other things required for 0.60.0 changes. I think I read a hunch of breaking changes happened for libraries?

May require I up version to v0.10.0 for 0.60.0 features so that it doesnt mess with anyone already going in <= 0.59.9 (ie me).

**Comment by iamandiradu** [comment]
I'm not sure if it is required. You can create a new branch that contains this fix and point it in the README file so that other 0.60ers can see it. :)

**Comment by kenjdavidson** [comment]
For sure. Will do when I have time this evening.

**Comment by kenjdavidson** [comment]
Merged pull request.
Updated README and package.json
Published v0.10.0 to NPM for the "0.60ers" out there.

Let me know how that goes, I didn't do anything other than your request and up version.

**Pull request merged**
