### PR TITLE
Add encoding parameter to BluetoothModule and BluetoothDevice write methods

### PR DESCRIPTION
**Pull request by AntonioDeCasper**
For my work project i need a different encoding type (not base64). So i decide make some improvements. This is my first pull request so don't be too strict :)

### CODE REVIEW

**Comment by kenjdavidson** [comment]
Thanks for the PR.

The issue here is that on the Native side, the data is being decoded from Base64.

**Android**
https://github.com/kenjdavidson/react-native-bluetooth-classic/blob/0f4c4eb8ef5e7f3d5eeb0bc73cf5848d60d07edf/android/src/main/java/kjd/reactnative/bluetooth/RNBluetoothClassicModule.java#L872

**IOS**
https://github.com/kenjdavidson/react-native-bluetooth-classic/blob/0f4c4eb8ef5e7f3d5eeb0bc73cf5848d60d07edf/ios/RNBluetoothClassic.swift#L399

I'm not entirely sure how if you're encoding this with `ascii` (lets say) on the Javascript side, that the native side is able to decode it properly and send the appropriate message? 

- Could you provide the example where this is being used? And decoded on then native side properly?

Essentially you shouldn't care how this is getting encoded, I wouldn't think using the following data flow:

1. Application calls `device.connect()` 
2. Application calls `device.write('this is some data') using a String for the most basic case. 
- 'this is some data' is base64 encoded
- If for example you encoded this as Ascii using your change
3. Native side attempts to decode the value
- as Bas64 it will be decoded properly
- as ascii it will not be decoded properly without changes to native
4. The native side actually writes this new string to the device (where it uses the correct encoding).

Without your actual use case it's hard to see whats up but:

```
let connected = await device.connect({ charset: 'ascii' });
```

Will cause:
1. Connect with charset
2. Call `device.write("this is some data")
3. "this is some data" as base64
4. decode "this is some data" as base64, which should give us our string back
5. Write "this is some data" to device using ascii

The end product is ascii gets written to the device.  If you're having an issue with this, we should definitely fix it.  But the Base64 just for communication to the Native side through the React Native bridge, and NOT to the device.

**Comment by AntonioDeCasper** [comment]
Sry, didnt see that on the Native side, the data is being decoded from Base64.
But i dont understand one thing. I write some data as Buffer:

`const data = Buffer.from([1,2,3,4]);
device.write(data).
`
and then in BluetoothModule that data will be encoded with base64. But we have condition:
`
if ("string" === typeof message) {
  data = Buffer.from(message);
} else {
  data = Buffer.from(message.toString());
}
`
Buffer.from(message.toString()) will change data that i was send. Or i something understand again?

**Comment by kenjdavidson** [comment]
Oh ya, the data's going to get all out of wack, the problem is you're going to need to unwackify it on the native side.   The only viable type for transferring data across the react bridge is String:

https://reactnative.dev/docs/native-modules-android#argument-types

So the goal is:

1) Get a the data into a consistent String value
2) Unwrap it in your `DeviceConnection`

The currently available `DeviceConnection` only expects String.  So regardless of the changes you make, you're going to need to write your own `DeviceConnection` for handling that data on the Native side.

If you look at the data processing, this is what happens on the React side:

```shell
> const message = Buffer.from([1,2,3,4]);
> message.toString()
'\u0001\u0002\u0003\u0004'
> const data = Buffer.from(message.toString());
> data.toString();
'\u0001\u0002\u0003\u0004'
> const sent = data.toString("base64");
> sent
'AQIDBA=='
```

So the Native (Java and IOS) get the string `AQIDBA==`.  When this is converted back to a String (which again is all we have to work with):

```java
            // At this point the data should be encoded correctly.  The original version did some
            // weird decoding and encoding but it didn't seem right.  At this point leaving it
            // as is and required to be set at the client level.
            byte[] data = Base64.decode(message, Base64.DEFAULT);
```

So you've got the `byte[]` that matches the original decoding: `'\u0001\u0002\u0003\u0004'`.  So ya, at this point the default will write that String to the device in the provided charset (ascii default, which is probably not what you want).  

If you want to write the unicode, you need to tell the native side that:

```js
let connected = await device.connect({ charset: 'utf-8' });  // Or whatever you want
```

So what exactly is getting written to the device?
And what exactly are you expecting to be written to the device?

**Comment by kenjdavidson** [comment]
Hey, so I took these changes and made them manually, with one other change that wasn't included.  So you should be able to call:

`device#write(data, encoding?)`

or 

`RNBluetoothClassic.writeToDevice(address, data, encoding?)`

which will now:

- If data is a Buffer it will leave it as is
- If data is anything else, it will encode using the provided encoding (utf8 as default, which is undefined anyhow)
- Finally this is still Base64 encoded to get across the React Native bridge

At this point, within the Java / IOS modules you will have:

`byte[] data = Base64.decode(message)`

You'll still need to create and assign a custom `DeviceConnection` in order to write this data to the device, the default `DelimitedStringDeviceConnectionImpl` will still attempt to convert this device to a string then write it as those bytes.

I've also added `ByteArrayDeviceConnectionImpl` which:
- Writes the byte[] as it was provided to Native side
- Reads the byte[] and passes the Base64 encoding of it.

So you'll still need to handle that in javascript correctly on the React Native side.

Please let me know.

**Comment by AntonioDeCasper** [comment]
Hey, thanks for update. It will help to write Buffer type wridth into device. That was i need :)



Now i saw another problem with receiving data from device. ```DelimitedStringDeviceConnectionImpl.java``` that used by default when we receive data have method:
```java
@Override
    protected void receivedData(byte[] bytes) {
        Log.d(this.getClass().getSimpleName(),
                String.format("Received %d bytes from device %s", bytes.length, getDevice().getAddress()));

        mBuffer.append(new String(bytes, mCharset));

        if (mOnDataReceived != null) {
            Log.d(this.getClass().getSimpleName(),
                    "BluetoothEvent.READ listener is registered, providing data");

            String message;
            while ((message = read()) != null) {
                mOnDataReceived.accept(getDevice(), message);
            }
        } else {
            Log.d(this.getClass().getSimpleName(),
                    "No BluetoothEvent.READ listeners are registered, skipping handling of the event");
        }
    }
```
But i receive "raw" data and operation `mBuffer.append(new String(bytes, mCharset));` return empty string for me.
Also i see that there is was added new class ```ByteArrayDeviceConnectionImpl``` with alternative ```receivedData``` method in last commit. That will solve my problem as i think, but how can i use that class instead of `DelimitedStringDeviceConnectionImpl`?

**Comment by kenjdavidson** [comment]
Documentation is a wonderful thing.  :P

At least I think so. Haha. You should be able to easily add it to your package in Android. IOS I haven't tried yet but it smuch more annoying. 

Keep me posted man. This week is rough for me, the byte array was don't quickly and will need some love. So feel free to pr it.

**Comment by kenjdavidson** [comment]
https://www.kenjdavidson.com/react-native-bluetooth-classic/android/rn-bluetooth-classic-package/

**Pull request closed without merging**
