### PR TITLE
Register typescript definitions in package.json

### LINKED ISSUE #37: Provide definition file
https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html

### LINKED ISSUE #63: Make a release with recent changes (typescript definitions)
Hi @kenjdavidson!

Would it be possible to make a release, so typescript definitions, that were merged into master, would go to npm?

### PR DESCRIPTION
**Pull request by egorshulga**
Fixes #37. Fixes #63

### CODE REVIEW

**Comment by egorshulga** [comment]
That was fast. Thanks @kenjdavidson!

**Comment by kenjdavidson** [comment]
Github makes it easy.  I can't publish to NPM until I finish work though.

**Comment by egorshulga** [comment]
That's OK, I will use direct link to github for today in my package.json

**Comment by kenjdavidson** [comment]
If you've been using this actively, have you run into issue #59 ?
I'm curious how many people it's affecting, and whether I need to rush to fix it?

**Comment by egorshulga** [comment]
Hm, I'm not facing the issue, at least for the moment. I managed to subscribe both to bluetooth enabled & disabled events successfully

**Pull request merged**
