### PR TITLE
Update compile sdk version

### PR DESCRIPTION
**Pull request by mrlmark**
Run gradle assistant
Apply recommended gradle changes
Fix errors

### CODE REVIEW

**Comment by mrlmark** [comment]
@kenjdavidson This now builds w/ 0.73 android. Mostly auto-generated gradle stuff as a result of some version bumps. I don't know enough about Android module development to know if any of this is _correct_, so feel free to reject this if it's junk and i'll just build from my own fork.

**Comment by kenjdavidson** [comment]
@mrlmark do you happen to have a coles notes version of what changed in the main `RNBluetoothClassicModule` class?  it looks like a bunch of prettier changes (awesome) but pretty annoying to try and look at what's changed for this version.

**Comment by kenjdavidson** [comment]
Was there no need to change the implementation?  The issue that was opened for 0.73 of react had an error stating that the overriding/implementation was wrong in that either a method was removed or added.  I didn't see anything that would have fixed this from what I can tell.

**Comment by mrlmark** [comment]
> Was there no need to change the implementation? The issue that was opened for 0.73 of react had an error stating that the overriding/implementation was wrong in that either a method was removed or added. I didn't see anything that would have fixed this from what I can tell.

Sorry yeah, android studio auto-formatted it, should have disabled it beforehand.

Imported "import com.facebook.react.BuildConfig"

Removed a few @Overrides that were no longer overriding anything

Fixed one "@ReactMetho" typo to "@ReactMethod"

**Comment by kenjdavidson** [comment]
Either I'm drunk or reading the PR wrong, but it looks like the incoming changes have `@ReactMetho`.  Am I crazy?

**Comment by kenjdavidson** [comment]
@mrlmark I think I see what's up, your branch is well behind main:

This branch is 
[3 commits ahead of](https://github.com/mrlmark/react-native-bluetooth-classic/compare/kenjdavidson%3Areact-native-bluetooth-classic%3Amain...gradle-changes-and-bug-fixes), 

[42 commits behind](https://github.com/mrlmark/react-native-bluetooth-classic/compare/gradle-changes-and-bug-fixes...kenjdavidson%3Areact-native-bluetooth-classic%3Amain) kenjdavidson/react-native-bluetooth-classic:main.

Do you remember how you branched that?  Looking at the `main` branch in your fork, it all looks good.  But this one is behind a bunch, which is probably accounting for some of the issues.  I can't accept it the way it is, but I really want to as it looks super close.

**Comment by kenjdavidson** [comment]
This PR and branch is all messed up.

**Pull request closed without merging**
